### Settings specific to the explorer app of this project ###

# List of QBO entities that the app deals with
QUERIABLE_ENTITIES = [
    'Account',
    # 'Attachable',
    # 'Batch',
    'Bill',
    'BillPayment',
    'Budget',
    # 'ChangeDataCapture',
    # 'Class',
    'CompanyInfo',
    'CreditMemo',
    'Customer',
    'Department',
    'Deposit',
    'Employee',
    'Estimate',
    'Invoice',
    'Item',
    'JournalEntry',
    'Payment',
    'PaymentMethod',
    # 'Preferences',
    'Purchase',
    'PurchaseOrder',
    'RefundReceipt',
    # 'Reports',
    'SalesReceipt',
    'TaxAgency',
    'TaxCode',
    'TaxRate',
    'TaxService',
    'Term',
    'TimeActivity',
    'Transfer',
    'Vendor',
    'VendorCredit'
]  # commented out those entities listed in Intuit's API Explorer for which python-quickbooks has no objects.
